---
- name: Copy bashrc
  become: yes
  copy:
    src: files/bashrc
    dest: "/home/{{ user }}/.bashrc"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644

- name: Copy env file
  become: yes
  copy:
    src: files/env10.sh
    dest: "/home/{{ user }}/env10.sh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: Install Extra Packages
  become: yes
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
  - golang
  - git
  - wget
  - net-tools
  - bind-utils
  - vim
  - iptables-services
  - bridge-utils
  - bash-completion
  - kexec-tools
  - sos
  - psacct

- name: Yum Upgrade All Packages
  become: yes
  yum:
    name: "*"
    state: latest
